#!/usr/bin/env zsh

typeset -A list
list=(
  "Exit"      "i3-msg exit"
  "Suspend"   "systemctl suspend"
  "Reboot"    "systemctl reboot"
  "Shutdown"  "systemctl poweroff -i"
)

if [[ -z "$@" ]]; then
  echo ${(k)list} | tr ' ' '\n'
else
  eval $list[$@]
fi
